# Generated by Django 4.2.20 on 2025-05-12 09:33

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLifePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_title', models.CharField(max_length=32)),
                ('intro_text', wagtail.fields.RichTextField()),
                ('quote', wagtail.fields.RichTextField()),
                ('activities_title', models.CharField(max_length=32)),
                ('clubs_title', models.CharField(max_length=32)),
                ('hero_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StudentLifePageHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Highlight title', max_length=32)),
                ('description', wagtail.fields.RichTextField(help_text='Highlight description')),
                ('link', models.URLField(blank=True, help_text='Highlight link')),
                ('image', models.ForeignKey(help_text='Highlight image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='life.studentlifepage')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLifePageClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Club name', max_length=32)),
                ('description', wagtail.fields.RichTextField(help_text='Club description')),
                ('image', models.ForeignKey(help_text='Club image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='life.studentlifepage')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLifePageActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Activity name', max_length=32)),
                ('description', wagtail.fields.RichTextField(help_text='Activity description')),
                ('image', models.ForeignKey(help_text='Activity image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='life.studentlifepage')),
            ],
        ),
    ]
