# Generated by Django 4.2.2 on 2023-06-07 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlogPage",
            new_name="NewsPage",
        ),
        migrations.DeleteModel(
            name="BlogIndexPage",
        ),
    ]
