# Generated by Django 4.2.2 on 2023-06-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_rename_blogpage_newspage_delete_blogindexpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspage",
            name="lang",
            field=models.CharField(default="zh", max_length=2),
        ),
    ]
