# Generated by Django 4.2.2 on 2023-06-10 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_newsindex_rename_newspage_news"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="lang",
        ),
    ]
