# Generated by Django 4.2.2 on 2023-06-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_news_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
