# Generated by Django 4.2.2 on 2023-06-15 08:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="JoinUs",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("join", models.CharField(default="", max_length=50)),
                ("student_title", models.CharField(default="", max_length=50)),
                ("student_content", wagtail.fields.RichTextField(default="")),
                ("student_join", models.CharField(default="", max_length=50)),
                ("faculty_title", models.CharField(default="", max_length=50)),
                ("faculty_content", wagtail.fields.RichTextField(default="")),
                ("faculty_join", models.CharField(default="", max_length=50)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
