# Generated by Django 4.2.3 on 2023-10-25 00:32

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('join_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinus',
            name='faculty_portal',
        ),
        migrations.RemoveField(
            model_name='joinus',
            name='student_portal',
        ),
        migrations.AddField(
            model_name='joinus',
            name='student_first_content',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='joinus',
            name='student_first_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='ImageCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('content', wagtail.fields.RichTextField(default='')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_cards', to='join_us.joinus')),
            ],
        ),
    ]
