# Generated by Django 4.2.2 on 2023-06-13 02:37

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('join_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinus',
            name='faculty_content',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='joinus',
            name='faculty_join',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='joinus',
            name='faculty_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='joinus',
            name='join',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='joinus',
            name='student_content',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='joinus',
            name='student_join',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='joinus',
            name='student_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
