# Generated by Django 4.2.3 on 2023-10-25 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('join_us', '0002_remove_joinus_faculty_portal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinus',
            name='student_first_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
