# Generated by Django 4.2.3 on 2023-10-25 02:06

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('join_us', '0003_joinus_student_first_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinus',
            name='faculty_card_content',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='joinus',
            name='faculty_card_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='joinus',
            name='faculty_card_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='joinus',
            name='faculty_epilogue',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='joinus',
            name='faculty_process_left',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='joinus',
            name='faculty_process_right',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='joinus',
            name='faculty_process_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='joinus',
            name='faculty_requirements_left',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='joinus',
            name='faculty_requirements_right',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='joinus',
            name='faculty_requirements_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='joinus',
            name='student_first_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
