# Generated by Django 4.2.2 on 2023-06-26 04:09

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("overview_title", models.CharField(default="", max_length=50)),
                ("overview_content", wagtail.fields.RichTextField(default="")),
                ("alumni_title", models.CharField(default="", max_length=50)),
                ("accreditation_title", models.CharField(default="", max_length=50)),
                ("accreditation_content", wagtail.fields.RichTextField(default="")),
                ("data_title", models.CharField(default="", max_length=50)),
                ("data_sub_title_1", models.CharField(default="", max_length=50)),
                ("data_content_1", models.CharField(default="", max_length=50)),
                ("data_sub_title_2", models.CharField(default="", max_length=50)),
                ("data_content_2", models.CharField(default="", max_length=50)),
                ("data_sub_title_3", models.CharField(default="", max_length=50)),
                ("data_content_3", models.CharField(default="", max_length=50)),
                ("data_sub_title_4", models.CharField(default="", max_length=50)),
                ("data_content_4", models.CharField(default="", max_length=50)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Alumnus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("content", wagtail.fields.RichTextField(default="")),
                ("image", models.ImageField(default="", upload_to="alumni/")),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni",
                        to="about_us.aboutus",
                    ),
                ),
            ],
        ),
    ]
