# Generated by Django 4.2.3 on 2023-08-01 01:54

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='accreditation_content',
            new_name='accreditation',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='overview_content',
            new_name='overview',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='accreditation_title',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='alumni_title',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='data_content_1',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='data_content_2',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='data_content_3',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='data_content_4',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='data_sub_title_1',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='data_sub_title_2',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='data_sub_title_3',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='data_sub_title_4',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='data_title',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='overview_title',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='carousel_images',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], null=True, use_json_field=True),
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('content', models.CharField(default='', max_length=50)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='about_us.aboutus')),
            ],
        ),
    ]
