# Generated by Django 4.2.2 on 2023-06-10 09:07

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='accreditation_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='accreditation_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='alumni_content_1',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='alumni_content_2',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='alumni_content_3',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='alumni_name_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='alumni_name_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='alumni_name_3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='alumni_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='data_content_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='data_content_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='data_content_3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='data_content_4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='data_sub_title_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='data_sub_title_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='data_sub_title_3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='data_sub_title_4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='data_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='overview_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='overview_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
