# Generated by Django 4.2.2 on 2023-09-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='icon',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
