# Generated by Django 4.2.2 on 2023-06-12 01:13

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_aboutus_accreditation_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='accreditation_content',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='alumni_content_1',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='alumni_content_2',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='alumni_content_3',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='overview_content',
            field=wagtail.fields.RichTextField(default=''),
        ),
    ]
