# Generated by Django 4.2.2 on 2023-09-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_stat_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='icon',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
