# Generated by Django 4.2.3 on 2023-08-01 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('about_us', '0002_rename_accreditation_content_aboutus_accreditation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnus',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
    ]
