# Generated by Django 4.2.3 on 2023-08-01 02:43

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_alter_alumnus_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='about_us.aboutus'),
        ),
    ]
