# Generated by Django 4.2.20 on 2025-05-03 11:53

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_query_searchpromotion_querydailyhits'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('top_title', models.CharField(max_length=32)),
                ('top_text', wagtail.fields.RichTextField()),
                ('intro_title', models.CharField(max_length=32)),
                ('intro_text', wagtail.fields.RichTextField()),
                ('statistics_title', models.CharField(max_length=32)),
                ('overview_title', models.CharField(max_length=32)),
                ('application_status_text', wagtail.fields.RichTextField()),
                ('steps_title', models.CharField(max_length=32)),
                ('application_form_link', models.URLField()),
                ('contact_title', models.CharField(max_length=32)),
                ('contact_description', models.CharField(max_length=256)),
                ('contact_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('hero_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AdmissionsPageStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('content', wagtail.fields.RichTextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='admissions.admissionspage')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionsPageStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=64)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='admissions.admissionspage')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionsPageOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('content', wagtail.fields.RichTextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='overview_items', to='admissions.admissionspage')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionsPageHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', wagtail.fields.RichTextField()),
                ('link', models.URLField(blank=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='admissions.admissionspage')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionsPageContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=256)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_phones', to='admissions.admissionspage')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionsPageContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_emails', to='admissions.admissionspage')),
            ],
        ),
    ]
