# Generated by Django 4.2.2 on 2023-06-15 08:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentLife",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("activities_title", models.CharField(default="", max_length=50)),
                ("activities_sub_title_1", models.CharField(default="", max_length=50)),
                ("activities_content_1", wagtail.fields.RichTextField(default="")),
                ("activities_sub_title_2", models.CharField(default="", max_length=50)),
                ("activities_content_2", wagtail.fields.RichTextField(default="")),
                ("activities_sub_title_3", models.CharField(default="", max_length=50)),
                ("activities_content_3", wagtail.fields.RichTextField(default="")),
                ("activities_sub_title_4", models.CharField(default="", max_length=50)),
                ("activities_content_4", wagtail.fields.RichTextField(default="")),
                ("activities_sub_title_5", models.CharField(default="", max_length=50)),
                ("activities_content_5", wagtail.fields.RichTextField(default="")),
                ("activities_sub_title_6", models.CharField(default="", max_length=50)),
                ("activities_content_6", wagtail.fields.RichTextField(default="")),
                ("clubs_title", models.CharField(default="", max_length=50)),
                ("clubs_sub_title_1", models.CharField(default="", max_length=50)),
                ("clubs_content_1", wagtail.fields.RichTextField(default="")),
                ("clubs_sub_title_2", models.CharField(default="", max_length=50)),
                ("clubs_content_2", wagtail.fields.RichTextField(default="")),
                ("clubs_sub_title_3", models.CharField(default="", max_length=50)),
                ("clubs_content_3", wagtail.fields.RichTextField(default="")),
                ("clubs_sub_title_4", models.CharField(default="", max_length=50)),
                ("clubs_content_4", wagtail.fields.RichTextField(default="")),
                ("clubs_sub_title_5", models.CharField(default="", max_length=50)),
                ("clubs_content_5", wagtail.fields.RichTextField(default="")),
                ("clubs_sub_title_6", models.CharField(default="", max_length=50)),
                ("clubs_content_6", wagtail.fields.RichTextField(default="")),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
