# Generated by Django 4.2.3 on 2023-08-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_life', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='bg_color',
            field=models.CharField(default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='club',
            name='color',
            field=models.CharField(default='black', max_length=10),
        ),
    ]
