# Generated by Django 4.2.2 on 2023-06-12 01:27

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student_life', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlife',
            name='activities_content_1',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='activities_content_2',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='activities_content_3',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='activities_content_4',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='activities_content_5',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='activities_content_6',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='activities_sub_title_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='activities_sub_title_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='activities_sub_title_3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='activities_sub_title_4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='activities_sub_title_5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='activities_sub_title_6',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='activities_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='clubs_content_1',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='clubs_content_2',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='clubs_content_3',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='clubs_content_4',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='clubs_content_5',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='clubs_content_6',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='clubs_sub_title_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='clubs_sub_title_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='clubs_sub_title_3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='clubs_sub_title_4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='clubs_sub_title_5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='clubs_sub_title_6',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentlife',
            name='clubs_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
