# Generated by Django 4.2.2 on 2023-06-12 01:18

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='curriculum_content_1',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='education',
            name='curriculum_content_2',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='education',
            name='curriculum_content_3',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='education',
            name='curriculum_sub_title_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='curriculum_sub_title_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='curriculum_sub_title_3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='curriculum_tilte',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='learning_methods_content_1',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='education',
            name='learning_methods_content_2',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='education',
            name='learning_methods_content_3',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='education',
            name='learning_methods_sub_title_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='learning_methods_sub_title_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='learning_methods_sub_title_3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='learning_methods_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='student_guidance_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='wonderful_moments_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
