# Generated by Django 4.2.2 on 2023-06-15 08:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("head", models.CharField(default="", max_length=50)),
                ("introduction_title", models.CharField(default="", max_length=50)),
                ("introduction", wagtail.fields.RichTextField(default="")),
                ("read_more", models.CharField(default="了解更多", max_length=50)),
                (
                    "education_philosophy_title",
                    models.CharField(default="", max_length=50),
                ),
                ("motto_title", models.CharField(default="", max_length=50)),
                ("motto_content", models.CharField(default="", max_length=50)),
                ("spirit_title", models.CharField(default="", max_length=50)),
                ("spirit_content", models.CharField(default="", max_length=50)),
                ("key_competency_title", models.CharField(default="", max_length=50)),
                ("key_competency_content", models.CharField(default="", max_length=50)),
                ("cultivation_title", models.CharField(default="", max_length=50)),
                ("cultivation_content", models.CharField(default="", max_length=50)),
                ("principal_message", models.CharField(default="", max_length=50)),
                (
                    "principal_avatar",
                    models.ImageField(null=True, upload_to="home/principal_avatar"),
                ),
                ("principal_name", models.CharField(default="", max_length=50)),
                ("meet_baid_title", models.CharField(default="", max_length=50)),
                (
                    "admission_results_title",
                    models.CharField(default="", max_length=50),
                ),
                ("admission_results_content", wagtail.fields.RichTextField(default="")),
                ("news_title", models.CharField(default="", max_length=50)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
