# Generated by Django 4.2.20 on 2025-05-03 11:53

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('wagtailcore', '0095_query_searchpromotion_querydailyhits'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_images', wagtail.fields.StreamField([('image', 0)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, null=True)),
                ('hero_subtitle', models.CharField(max_length=128)),
                ('intro_title', models.CharField(max_length=32)),
                ('intro_text', wagtail.fields.RichTextField()),
                ('motto_title', models.CharField(max_length=32)),
                ('motto_content', wagtail.fields.RichTextField()),
                ('spirit_title', models.CharField(max_length=32)),
                ('spirit_content', wagtail.fields.RichTextField()),
                ('literacy_title', models.CharField(max_length=32)),
                ('literacy_content', wagtail.fields.RichTextField()),
                ('pathway_title', models.CharField(max_length=32)),
                ('pathway_content', wagtail.fields.RichTextField()),
                ('principal_quote', wagtail.fields.RichTextField()),
                ('principal_name', models.CharField(max_length=32)),
                ('literacy_bg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('motto_bg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('pathway_bg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('principal_avatar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('spirit_bg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePageHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Highlight title', max_length=32)),
                ('description', wagtail.fields.RichTextField(help_text='Highlight description')),
                ('link', models.URLField(blank=True, help_text='Highlight link')),
                ('image', models.ForeignKey(help_text='Highlight image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='home.homepage')),
            ],
        ),
    ]
