# Generated by Django 4.2.2 on 2023-09-16 12:13

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_carousel_images_alter_home_principal_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='cultivation_content',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='home',
            name='introduction_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='key_competency_content',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='home',
            name='motto_content',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='home',
            name='spirit_content',
            field=wagtail.fields.RichTextField(default=''),
        ),
    ]
