# Generated by Django 4.2.2 on 2023-06-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='head',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='lang',
            field=models.CharField(default='zh', max_length=2),
        ),
    ]
