# Generated by Django 4.2.2 on 2023-06-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_head_homepage_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='head',
            field=models.CharField(default='欢迎来到北京中学国际部！', max_length=50),
        ),
    ]
