# Generated by Django 4.2.2 on 2023-06-08 03:53

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
