# Generated by Django 4.2.2 on 2023-06-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='introduction_title',
            field=models.CharField(default='我们是北京中学国际部', max_length=50),
        ),
    ]
