# Generated by Django 4.2.2 on 2023-06-08 23:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("home", "0008_alter_homepage_admission_results_content_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HomePage",
            new_name="Home",
        ),
    ]
