# Generated by Django 4.2.2 on 2023-06-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_homepage_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='lang',
        ),
    ]
