# Generated by Django 4.2.2 on 2023-06-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_alter_home_admission_results_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="principal_avatar",
            field=models.ImageField(null=True, upload_to="home/principal_avatar"),
        ),
    ]
